// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzamgeekhujhorkggjnl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6YW1nZWVraHVqaG9ya2dnam5sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg3NjUwNDQsImV4cCI6MjA1NDM0MTA0NH0.eUVbBLd16KBqG4SFZg-OBNK34MRb3Zl6zujnvTABxzw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);